#
# Module manifest for module 'garuda-eye'
#
# Generated by: jokourno
#
# Generated on: 15/6/2026
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '871552ba-fc33-4f68-8452-b106dd67d015'

# Author of this module
Author = 'Joko Purnomo'


# Copyright statement for this module
Copyright = '(c) Joko Purnomo. All rights reserved.'

# Description of the functionality provided by this module
# Description = 'PowerShell-based, multithreaded alternative to Nmap'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = '5.1'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @(Nmap, Port, Scanner, Discovery, Network)

        # A URL to the license for this module.
        # LicenseUri = 'https://github.com/jokourno12/Garuda_Eye/tree/main?tab=GPL-3.0-1-ov-file'

        # A URL to the main website for this project.
        # ProjectUri = 'https://github.com/jokourno12/Garuda_Eye'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

    } # End of PSData hashtable

} # End of PrivateData hashtable

}